ast_build.o: cc.ast.gen.h
astvisit.o: cc.ast.gen.h
baselexer.o: lexer.yy.h
builtinops.o: cc.ast.gen.h
cc-ast-aux.o: cc.ast.gen.h
cc-elaborate.o: cc.ast.gen.h
cc-env.o: cc.ast.gen.h
cc-print.o: cc.ast.gen.h
cc-scope.o: cc.ast.gen.h
cc-tcheck.o: cc.ast.gen.h
cc-type-visitor.o: cc.ast.gen.h
cc-type.o: cc.ast.gen.h
cc.gr.gen.o: cc-tokens.h
cc.gr.gen.o: cc.ast.gen.h
ccparse.o: cc.ast.gen.h
cfg.o: cc.ast.gen.h
clang-import.o: cc.ast.gen.h
const-eval.o: cc.ast.gen.h
elsaparse.o: cc-tokens.h
elsaparse.o: cc.ast.gen.h
elsaparse.o: cc.gr.gen.h
elsaparse.o: lexer.yy.h
gnu.o: cc.ast.gen.h
implconv.o: cc.ast.gen.h
implint.o: cc.ast.gen.h
integrity.o: cc.ast.gen.h
iptparse.o: iptparse.yy.h
kandr.o: cc.ast.gen.h
lexer.o: cc-tokens.h
lexer.o: lexer.yy.h
lexer.yy.o: cc-tokens.h
main.o: cc.ast.gen.h
mangle.o: cc.ast.gen.h
mtype.o: cc.ast.gen.h
overload.o: cc.ast.gen.h
parssppt.o: cc-tokens.h
parssppt.o: lexer.yy.h
semgrep.o: cc-tokens.h
semgrep.o: cc.ast.gen.h
semgrep.o: cc.gr.gen.h
semgrep.o: lexer.yy.h
smin.o: iptparse.yy.h
sprint.o: cc.ast.gen.h
stdconv.o: cc.ast.gen.h
subobject-access-path.o: cc.ast.gen.h
template.o: cc.ast.gen.h
test-astbuild.o: cc.ast.gen.h
tlexer.o: cc-tokens.h
tlexer.o: lexer.yy.h
type-printer.o: cc.ast.gen.h
typelistiter.o: cc.ast.gen.h
ubermods-attrspec.o: cc.ast.gen.h
