ast_build.o: cc.ast.gen.h
astvisit.o: cc.ast.gen.h
baselexer.o: lexer.yy.h
builtinops.o: cc.ast.gen.h
cc.gr.gen.o: cc.ast.gen.h
cc.gr.gen.o: cc_tokens.h
cc_ast_aux.o: cc.ast.gen.h
cc_elaborate.o: cc.ast.gen.h
cc_env.o: cc.ast.gen.h
cc_print.o: cc.ast.gen.h
cc_scope.o: cc.ast.gen.h
cc_tcheck.o: cc.ast.gen.h
cc_type.o: cc.ast.gen.h
ccparse.o: cc.ast.gen.h
cfg.o: cc.ast.gen.h
const_eval.o: cc.ast.gen.h
gnu.o: cc.ast.gen.h
implconv.o: cc.ast.gen.h
implint.o: cc.ast.gen.h
integrity.o: cc.ast.gen.h
iptparse.o: iptparse.yy.h
kandr.o: cc.ast.gen.h
lexer.o: cc_tokens.h
lexer.o: lexer.yy.h
lexer.yy.o: cc_tokens.h
main.o: cc.ast.gen.h
main.o: cc.gr.gen.h
main.o: cc_tokens.h
main.o: lexer.yy.h
main.o: xml_enum_1.gen.h
main.o: xml_lex.gen.yy.h
mangle.o: cc.ast.gen.h
mtype.o: cc.ast.gen.h
notopt.o: cc.ast.gen.h
overload.o: cc.ast.gen.h
parssppt.o: cc_tokens.h
parssppt.o: lexer.yy.h
semgrep.o: cc.ast.gen.h
semgrep.o: cc.gr.gen.h
semgrep.o: cc_tokens.h
semgrep.o: lexer.yy.h
smin.o: iptparse.yy.h
sprint.o: cc.ast.gen.h
stdconv.o: cc.ast.gen.h
template.o: cc.ast.gen.h
tlexer.o: cc_tokens.h
tlexer.o: lexer.yy.h
typelistiter.o: cc.ast.gen.h
xml_ast_reader.o: cc.ast.gen.h
xml_ast_reader.o: xml_ast_reader_0decl.gen.h
xml_ast_reader.o: xml_ast_reader_1defn.gen.cc
xml_ast_reader.o: xml_ast_reader_2ctrc.gen.cc
xml_ast_reader.o: xml_ast_reader_3regc.gen.cc
xml_ast_reader.o: xml_enum_1.gen.h
xml_ast_reader.o: xml_lex.gen.yy.h
xml_do_read.o: cc.ast.gen.h
xml_do_read.o: xml_ast_reader_0decl.gen.h
xml_do_read.o: xml_enum_1.gen.h
xml_do_read.o: xml_lex.gen.yy.h
xml_file_reader.o: xml_enum_1.gen.h
xml_file_reader.o: xml_lex.gen.yy.h
xml_lexer.o: xml_enum_1.gen.h
xml_lexer.o: xml_lex.gen.yy.h
xml_lexer.o: xml_name_1.gen.cc
xml_lexer.yy.o: xml_enum_1.gen.h
xml_lexer.yy.o: xml_lex.gen.yy.cc
xml_lexer.yy.o: xml_lex.gen.yy.h
xml_reader.o: xml_enum_1.gen.h
xml_reader.o: xml_lex.gen.yy.h
xml_type_reader.o: xml_enum_1.gen.h
xml_type_reader.o: xml_lex.gen.yy.h
xml_type_writer.o: cc.ast.gen.h
