ast_build.o: cc.ast.gen.h
astvisit.o: cc.ast.gen.h
baselexer.o: lexer.yy.h
builtinops.o: cc.ast.gen.h
cc.gr.gen.o: cc.ast.gen.h
cc.gr.gen.o: cc_tokens.h
cc_ast_aux.o: cc.ast.gen.h
cc_elaborate.o: cc.ast.gen.h
cc_env.o: cc.ast.gen.h
cc_print.o: cc.ast.gen.h
cc_scope.o: cc.ast.gen.h
cc_tcheck.o: cc.ast.gen.h
cc_type.o: cc.ast.gen.h
ccparse.o: cc.ast.gen.h
cfg.o: cc.ast.gen.h
const_eval.o: cc.ast.gen.h
gnu.o: cc.ast.gen.h
implconv.o: cc.ast.gen.h
implint.o: cc.ast.gen.h
integrity.o: cc.ast.gen.h
iptparse.o: iptparse.yy.h
kandr.o: cc.ast.gen.h
lexer.o: cc_tokens.h
lexer.o: lexer.yy.h
lexer.yy.o: cc_tokens.h
main.o: cc.ast.gen.h
main.o: cc.gr.gen.h
main.o: cc_tokens.h
main.o: lexer.yy.h
mangle.o: cc.ast.gen.h
mtype.o: cc.ast.gen.h
overload.o: cc.ast.gen.h
parssppt.o: cc_tokens.h
parssppt.o: lexer.yy.h
semgrep.o: cc.ast.gen.h
semgrep.o: cc.gr.gen.h
semgrep.o: cc_tokens.h
semgrep.o: lexer.yy.h
smin.o: iptparse.yy.h
sprint.o: cc.ast.gen.h
stdconv.o: cc.ast.gen.h
template.o: cc.ast.gen.h
tlexer.o: cc_tokens.h
tlexer.o: lexer.yy.h
typelistiter.o: cc.ast.gen.h
